### ISSUE TITLE
Would it be possible to color only background of the indentation, before first word?

### ISSUE THREAD

**Issue by Millani** [thiagoalessio/rainbow_levels.vim#11]
I am wondering if it would be possible to set the plug in up such that only the background of the indentations themselves, that is before the first word of each line. As an example, see the (analogously named) Visual Studio Code extension:
https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow

Thanks!

**Comment by thiagoalessio** [comment]
not possible with the current implementation, but with a few modifications on the matching patterns you could achieve the desired behavior.
