### ISSUE TITLE
RainbowLevel only incremented by 8 spaces, not 4?

### ISSUE THREAD

**Issue by itdaniher** [thiagoalessio/rainbow_levels.vim#12]
Hello, and thanks for such a pleasant improvement to my workflow! Combined with https://github.com/luochen1990/rainbow, it feels like having x-ray vision!

I write a lot of Python, keeping with [PEP8](https://www.python.org/dev/peps/pep-0008/#indentation) which recommends 4 spaces per indent level.

In my vimrc, I have:

```
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smarttab
```
amongst other lines...

Unfortunately, it seems as if `rainbow_levels.vim` only increments the "RainbowLevel" in increments of 8 spaces. This can be seen in the screenshot below.

![2019-01-23-162830_402x208_scrot](https://user-images.githubusercontent.com/22683/51638282-f79fa380-1f2b-11e9-85c0-0f91dc4a212b.png)

It would be quite nice if the RainbowLevel was incremented every indent level, rather than every other indent level - any idea what I'm doing wrong?

Thanks!

**Comment by thiagoalessio** [comment]
Hello @itdaniher do you have `set expandtab` or `set noexpandtab` ?

**Comment by itdaniher** [comment]
I noodled on my vimrc, tried a few things, and figured it out!

I had:

```
filetype plugin indent on
```

in my vimrc from days past. Removing it results in the correct behavior as per the attached screenshot.


![2019-01-24-005027_510x479_scrot](https://user-images.githubusercontent.com/22683/51657264-1fb1f580-1f72-11e9-9e01-afa400a2e5e2.png)

Thanks for a wonderful tool!
