### ISSUE TITLE
jellybeans level2/3 are too similar

### ISSUE THREAD

**Issue by mmikeww** [thiagoalessio/rainbow_levels.vim#2]
The suggested jellybeans config has levels 2 and 3 almost the same, its so hard to differentiate. Should be changed IMO

**Comment by mmikeww** [comment]
Actually, same for solarized and birds of paradise, judging by the screenshots

perhaps an orange should be swapped in for level 3

**Comment by thiagoalessio** [comment]
I agree! Just did those examples like that to have a "rainbow" effect.

If you want you can use the theme colors but changing the sequence to have a better contrast, like this one: https://github.com/thiagoalessio/rainbow_levels.vim/wiki/User-Contributed-Themes#oceanic-next
