### ISSUE TITLE
Support of softtabstop indenting

### ISSUE THREAD

**Issue by inkarkat** [thiagoalessio/rainbow_levels.vim#6]
This plugin is a great idea. Unfortunately, so far only indenting with pure tabs or spaces seems to be supported. Vim has a third method via `:set softtabtop=...`); it uses tabs (with a fixed width of 8) followed by spaces for fractions of tabs.

Basically, you need to extend `rainbow_levels#is_indented_with_tabs()` and `rainbow_levels#get_indent_size()`. By the way, the latter uses `'shiftwidth'` for non-tab indent; that option is purely for shifting with `>` and `<` (but usually aligned with the indent settings). Use `'tabstop'` value also for `'expandtab'`. For soft tabstops, use the `'softtabtop'` instead.

PS: I've refrained from fixing this and submitting a pull request, because it would affect larger parts of your plugin. I don't want to take away your ownership of this nice piece of code.

**Comment by thiagoalessio** [comment]
Hum, I only dealt with pure tabs or pure spaces so far, didn't consider the mix ... will check that, maybe write some tests as well.

And please, I really don't mind about ownership, now it belongs to all of us vim lovers ;D
Your contributions are really making this plugin better for everyone, so by all means, place as many PRs as you feel like it.

**Comment by inkarkat** [comment]
Thanks! I'm also wondering how irregular tab + space + tab combinations should be handled, or if you have an indent setting of 4 spaces but use 5 (or 6) spaces. So far, they would not be colored at all, which I like: It makes those lines stand out, because they are wrong.

**Comment by thiagoalessio** [comment]
It should keep the color until it reaches the amount of spaces required:

<img width="509" alt="screen shot 2017-12-20 at 17 31 38" src="https://user-images.githubusercontent.com/190616/34217457-d910c314-e5ab-11e7-8cc9-2acb5dfaf8d6.png">

Are you having a different effect on your env?

**Comment by inkarkat** [comment]
Oh yeah, you're right. It's just for tabs that additional spaces are now allowed, but that's exactly the soft tabstop use case this issue is about.

**Comment by thiagoalessio** [comment]
I managed to get some feedback from colleagues that also happen to deal with mixed tabs+spaces, seems to be working as expected with PR#7.

If I missed some case please feel free to reopen this issue ;D
